name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - name: github page repo
      uses: actions/checkout@v3
      with: 
          repository: zanllp/zanllp.github.io
          path: build
    - uses: actions/checkout@v2
      with: 
          path: main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: download dependencies
      working-directory: ${{github.workspace}}/main
      run: |
        npm i
    - name:  build
      working-directory: ${{github.workspace}}/main
      run: |
        npm run build 
    - name: copy released file
      working-directory: ${{github.workspace}}/main/dist
      run: cp -R . ../../build
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
          commit-message: Update released files
          title: Update released files
          branch: update-released-files
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          delete-branch: true
          body: Triggered by [${{ github.sha }}](https://github.com/zanllp/extendable-viewer/commit/${{ github.sha }})
          path: ${{github.workspace}}/build
          token: ${{ secrets.PAT }}
          reviewers: zanllp
