name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: c-hive/gha-yarn-cache@v1
    - name: download dependencies
      run: yarn
    - name:  build
      run: yarn build 
    - name: init git
      run: |
        git init
        git add --all
        git remote add origin git@github.com:zanllp/zanllp.github.io.git
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
          commit-message: update authors
          title: Update AUTHORS
          body: Credit new contributors by updating AUTHORS
          branch: update-authors
          path: dist
