name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with: 
          repository: zanllp/zanllp.github.io
          path: build
    - uses: actions/checkout@v2
      with: 
          repository: zanllp/zanllp.github.io
          path: main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: download dependencies
      working-directory: ${{github.workspace}}/main
      run: npm i
    - name:  build
      working-directory: ${{github.workspace}}/main
      run: npm run build 
    - name: copy released file
      working-directory: ${{github.workspace}}/main/dist
      run: cp -R . ../../build
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with: 
          repository: zanllp/zanllp.github.io
          path: build
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
          commit-message: update authors
          title: Update AUTHORS
          body: Credit new contributors by updating AUTHORS
          branch: update-authors
          path: dist
